[package]
name = "osc_address_macros"
version = "0.1.0"
authors = ["Colin Wallace <wallacoloo@gmail.com>"]

[dependencies]
syn = "0.11"
quote = "0.3"
osc_address = { version = "0.2.0", path = "../osc_address" }

[lib]
proc-macro = true
